name: Dependency Diff

on:
  workflow_dispatch: {}

jobs:
  extract-updated-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract dependencies
        run: |
          mkdir -p build/dependencies
          projects=(./gradlew -q projects)
          echo $projects | while read line ; do
              if [[ $line =~ "--- Project" ]]; then
                  project=${${line#*Project \'}%\'*}
                  echo "Exporting $project dependencies"; 
                  ./gradlew $project:dependencies </dev/null > build/dependencies/$project.txt
                  cat build/dependencies/$project.txt
              fi
          done
