name: Dependency Diff

on:
  workflow_dispatch: {}

jobs:
  extract-updated-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract dependencies
        run: |
          echo "::notice start"
          mkdir -p build/dependencies
          projects=$(./gradlew -q projects)
          echo "::notice $projects"
          echo $projects | while read -r line ; do
              if [[ $line =~ "--- Project" ]]; then
                  project=${line:14:-1}
                  echo "::notice Exporting $project dependencies"; 
                  ./gradlew $project:dependencies </dev/null > build/dependencies/$project.txt
                  echo "::notice ${cat build/dependencies/$project.txt}"
              fi
          done
